name: Python Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Reposuyu klonla
      uses: actions/checkout@v4

    - name: Python'u kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Testleri çalıştır
      run: |
        pytest
run-name: 
